### ISSUE TITLE
Used in other species

### ISSUE THREAD

**Issue by sanderslhc** [sulab-wmu/scPagwas#15]
Hi, thank you for providing a great software! I want to know if this software can be used in the GWAS data from other species?

**Comment by dengchunyu** [comment]
Yes, however, preliminary calculations are necessary. If you intend to
utilize GWAS data from other species, it is essential to substitute the
"block_annotation" in the code with gene annotation information in a
compatible format and specific to the corresponding species' GWAS data.
Additionally, prior LD calculation and SNP filtering of the annotation
information using ‘plink’ are required. By following these steps, scPagwas
can be computed effectively.

Sanders Li ***@***.***> 于2023年11月10日周五 23:49写道：

**Comment by dengchunyu** [comment]
Revision: plink calculation is to filter gwas file of other species, mainly
filtering high LD snps.  The purpose of this step is to avoid the
filtration of human LD information during the scPagwas calculation process,
which means that this step is performed in advance so that subsequent
calculations will not be affected.

邓春玉 ***@***.***> 于2023年11月13日周一 10:13写道：
