### ISSUE TITLE
Error when mapping file:

### ISSUE THREAD

**Issue by cyclovecqh** [sulab-wmu/scPagwas#8]
I am very grateful to you for developing this software.The software is very simple and feasible.However,I have a problem.
When I run "Link_pathway_blocks_gwas" ，the result returned 
* Start to link gwas and pathway block annotations for 309 pathways!
  |                                                                      |   0Creating directory "./scPaGWAS/temp" which didn't exist..
错误: Error when mapping file:
  无效的参数.
I hope someone can solve my problem

**Comment by dengchunyu** [comment]
At the beginning of the main function in scPagwas, a temporary folder is
automatically created. This is done to establish a cache file storage
location, preventing the excessive consumption of system memory by cache
files.
Usually, R automatically creates a "temp" folder, but in this case, it
appears not to have been created. You can manually create the "temp" folder
within your scPagwas directory. Or, use the following code:

#The following code snippet checks if a "temp" folder exists. If it doesn't
exist, it creates one. Additionally, it checks if there are any ".bk" files
inside the folder and removes them if found.
if (dir.exists(paste0("./", output.dirs, "/temp"))) {
    temp_folder_path <- paste0("./", output.dirs, "/temp")
    files_to_remove <- list.files(temp_folder_path)
    invisible(file.remove(file.path(temp_folder_path, files_to_remove)))
    cat("bk files has been deleted")
  }else{
dir.create(paste0("./", output.dirs, "/temp"))
}
Pagwas <- Link_pathway_blocks_gwas(
      Pagwas = Pagwas,
      chrom_ld = chrom_ld,
      singlecell = T,
      celltype = T,
      backingpath=paste0("./", output.dirs, "/temp"),
      n.cores=1
      )
To prevent others from encountering this issue in the future, I will
include the code to create the folder in the next update. Thank you for
your feedback.

cyccqh ***@***.***> 于2023年9月4日周一 22:35写道：

**Comment by cyclovecqh** [comment]
Thank you very much for your prompt response.I have solved the problem I raised earlier.In fact, it was because I wasn't fully prepared for the GWAS data.I downloaded the sample GWAS file and knew what I needed.
I have finished the work and try to visualize it.I've got two problems I can't solve
**The first one is** 
In my Pagwas.Rdata,I can not find 3 dimensional reductions calculated: pca, tsne, umap
```
An object of class Seurat
35587 features across 34004 samples within 3 assays
Active assay: RNA (34987 features, 0 variable features)
 2 other assays present: scPagwasPaHeritability, scPagwasPaPca
```
Did I make a mistake with my previous steps？
The previous log file shows `There were 50 or more warnings (use warnings() to see the first 50)`
**The second one is** 
In Plot the barplot of the proportion of positive Cell ，my plot don‘t show different types of cell.In fact,it only
shows one name NA.
My code is
```
plot_bar_positie_nagtive(seurat_obj=Pagwas,
+                          var_ident="celltypes",
+                          var_group="positiveCells",
+                          vec_group_colors=c("#E8D0B3","#7EB5A6"),
+                          do_plot = T)
Warning messages:
1: In as.data.table.list(x, keep.rownames = keep.rownames, check.names = check.names,  :
  Item 1 has 0 rows but longest item has 34004; filled with NA
2: In order(.) : 强制改变过程中产生了NA
```
I think the problem is ’var ident‘.
I'd appreciate it if anyone could give me some advice.

**Comment by dengchunyu** [comment]
font{
        line-height: 1.6;
    }
    ul,ol{
        padding-left: 20px;
        list-style-position: inside;
    }


    
    For the first question:
The output Pagwas.Rdata file follows a format similar to your input single-cell data. If your input single-cell data did not have PCA, t-SNE, or UMAP calculated, then them will not be present in the output Pagwas data either. You can proceed calculation on Pagwas data for visualization, similar to the following:
```r
Pagwas <- RunPCA(Pagwas, npcs = 30) 
#Pagwas is your output for scPagwas!Pagwas <- FindNeighbors(Pagwas, dims = 1:30)
Pagwas <- FindClusters(Pagwas, resolution = 0.5)
Pagwas <- RunUMAP(Pagwas, dims = 1:30)
```For subsequent plotting, you can also directly use Seurat package's plotting functions, for example:

```r
Seurat::FeaturePlot(Pagwas, features = "scPagwas.TRS.Score1")
```For the second question, the var_ident="celltypes" parameter in the example data is used to specify the column name containing cell type annotations or other group you want to visualize. This parameter should be changed according to the specific column in your own data. You can check the ***@***.***) to choose the appropriate column for your plotting.
    
     
    
        
                    ***@***.***
        
    
 

  
    ---- Replied Message ----
  
  
    
      
        
         From 
        
        
            ***@***.***>
            
        
      
      
        
         Date 
        
        
        9/7/2023 22:20
        
      
      
        
         To 
        
        
         
          
            ***@***.***>
            
          
        
      
      
        
         Cc 
        
        
          
            Chunyu ***@***.***>
            ,
          
          
            ***@***.***>
            
          
        
      
      
        
         Subject 
        
        
              Re: [sulab-wmu/scPagwas] Error when mapping file: (Issue #8)
        
      
    
  
  
Thank you very much for your prompt response.I have solved the problem I raised earlier.In fact, it was because I wasn't fully prepared for the GWAS data.I downloaded the sample GWAS file and knew what I needed.
I have finished the work and try to visualize it.I've got two problems I can't solve
The first one is
In my Pagwas.Rdata,I can not find 3 dimensional reductions calculated: pca, tsne, umap
An object of class Seurat
35587 features across 34004 samples within 3 assays
Active assay: RNA (34987 features, 0 variable features)
 2 other assays present: scPagwasPaHeritability, scPagwasPaPca

Did I make a mistake with my previous steps？
The previous log file shows There were 50 or more warnings (use warnings() to see the first 50)
The second one is
In Plot the barplot of the proportion of positive Cell ，my plot don‘t show different types of cell.In fact,it only
shows one name NA.
My code is
plot_bar_positie_nagtive(seurat_obj=Pagwas,
+                          var_ident="celltypes",
+                          var_group="positiveCells",
+                          vec_group_colors=c("#E8D0B3","#7EB5A6"),
+                          do_plot = T)
Warning messages:
1: In as.data.table.list(x, keep.rownames = keep.rownames, check.names = check.names,  :
  Item 1 has 0 rows but longest item has 34004; filled with NA
2: In order(.) : 强制改变过程中产生了NA

I think the problem is ’var ident‘.
I'd appreciate it if anyone could give me some advice.

—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you commented.Message ID: ***@***.***>

**Comment by cyclovecqh** [comment]
Thank you for your patient reply, my problem has been solved, I will close this discussion
